---
- hosts: webserver, webserver_debian
  remote_user: ansible
  tasks:
    - name: Print the ansible_os_family value
      debug:
        msg: '{{ ansible_os_family }}'
    - name: Ensure the httpd package is updated
      yum:
        name: httpd
        state: latest
      become: True
      when: ansible_os_family == 'RedHat'
    - name: Ensure the apache2 package is updated
      apt:
        name: apache2
        state: latest
      become: True
      # Condition can be ==, !=, >, >=, <, <=, in, and not.
      # Condition can use and, or to combine mulitple situations 
      when: ansible_os_family == 'Debian'
