---
- hosts: localhost
  connection: local
  tasks:
    - name: Read the machine uptime
      command: uptime -p
      register: uptime
    - name: Send the uptime to SNS
      sns:
        msg: "Local system uptime is {{ uptime.stdout }}"
        subject: "System uptime"
        topic: "ansible-notification"
