---
- hosts: all
  remote_user: ansible
  tasks:
    - name: Create the folders /tmp/dirXY with XY from 1 to 10
      file:
        dest: '/tmp/dir{{ item }}'
        state: directory
      become: True
      # with_sequence only support single notation
      with_sequence: start=1 end=10
