---
- hosts: localhost
  connection: local
  vars:
    user_ok: root
    user_ko: leaf
  tasks:
    - name: "Check if user {{ user_ok }} exists"
      check_user:
        user: "{{ user_ok }}"
    - name: "Check if user {{ user_ko }} exists"
      check_user:
        user: "{{ user_ko }}"
