---
- hosts: localhost
  connection: local
  vars:
    user_ok: root
    user_ko: twice
  tasks:
    - name: "Check if user {{user_ok}} exists"
      check_user_final:
        user: "{{user_ok}}"
    - name: "Check if user {{user_ko}} exists"
      check_user_final:
        user: "{{user_ko}}"
