---
- hosts: all
  remote_user: ansible
  tasks:
    - name: Ensure we have last version of every package
      yum:
        name: "*"
        state: latest
      become: True
    - name: Ensure EPEL is enabled
      yum:
        name: epel-release
        state: present
      become: True
    - name: Ensure libselinux-python is present
      yum:
        name: libselinux-python
        state: present
      become: True
    - name: Ensure libsemanage-python is present
      yum:
        name: libsemanage-python
        state: present
      become: True
    - name: Ensure the timezone is set to Toronto
      file:
        src: /usr/share/zoneinfo/America/Toronto
        dest: /etc/localtime
        state: link
      become: True
    - name: Ensure NTP is installed
      yum:
        name: chrony
        state: present
      become: True
    - name: Ensure the NTP service is running and enabled
      service:
        name: chronyd
        state: started
        enabled: True
      become: True
    - name : Ensure Firewalld is installed
      yum:
        name: firewalld
        state: present
      become: True
    - name: Ensure SSH can pass the firewall
      firewalld:
        service: ssh
        state: enabled
        permanent: True
      become: True
    - name: Ensure Firewalld is running
      service:
        name: firewalld
        state: started
        enabled: True
      become: True
    - name: Ensure the hostname is the same of the inventory
      hostname:
        name: "{{ inventory_hostname }}"
      become: True
