---
- hosts: all
  remote_user: ansible
  vars:
    users:
      - clive
      - chihwei
    folders:
      - mail
      - public_html
  tasks:
    - name: Ensure the users exist
      user:
        name: '{{ item }}'
        state: present
      become: True
      with_items:
        - '{{ users }}'
    - name: Ensure the folders exists
      file:
        path: '/home/{{ item.0 }}/{{ item.1 }}'
        state: directory
        owner: '{{ item.0 }}'
        group: '{{ item.0 }}'
      become: True
      with_nested:
        - '{{ users }}'
        - '{{ folders }}'
