---
- hosts: webserver
  remote_user: ansible
  tasks:
    - name: Ensure the website is presebt and updated
      template:
        src: index.html.template
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      become: True
